In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,5,7], dtype ='i') 

In [3]:
b = np.array((2,3,5), dtype = 'f') #change to f

In [4]:
a.dtype

dtype('int32')

In [5]:
b.dtype

dtype('float32')

#Numpy (Dimension)

In [6]:
a = np.array([[1,2,3], [4,5,6]])

In [7]:
a.ndim

2

In [8]:
a[0,2]

np.int64(3)

In [9]:
B = np.array([[1,2,3,0], [2,4,5,9]], dtype='i')

In [10]:
B[1,2]

np.int32(5)

In [11]:
c = np.array ([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [12]:
c.ndim

3

In [13]:
c[1,0,2]

np.int64(-3)

In [14]:
c.shape

(2, 3, 3)

NUMPY (np.arange, reshape, random)

In [15]:
#np.arange
A = np.arange(20,100,3) #start, end, jump
                        #same as "for i in range(20:10:3)

In [16]:
print(A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [17]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
#np.random
A = np.random.permutation(np.arange(10))
print (A)

[5 8 0 7 1 2 6 4 3 9]


In [19]:
#np.reshape
A = np.arange(100).reshape(4,25)

In [20]:
A.shape

(4, 25)

 Numpy(Slicing)

In [21]:
A = np.arange(100)

In [22]:
b = A[3:10]
print(b)

[3 4 5 6 7 8 9]


In [23]:
b[0] = -1200

In [24]:
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [25]:
A #ikut berubah

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [26]:
#untuk mencegah dari perubahan
b = A[3:10].copy()

In [27]:
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [28]:
A[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [29]:
A[::-1]

array([   99,    98,    97,    96,    95,    94,    93,    92,    91,
          90,    89,    88,    87,    86,    85,    84,    83,    82,
          81,    80,    79,    78,    77,    76,    75,    74,    73,
          72,    71,    70,    69,    68,    67,    66,    65,    64,
          63,    62,    61,    60,    59,    58,    57,    56,    55,
          54,    53,    52,    51,    50,    49,    48,    47,    46,
          45,    44,    43,    42,    41,    40,    39,    38,    37,
          36,    35,    34,    33,    32,    31,    30,    29,    28,
          27,    26,    25,    24,    23,    22,    21,    20,    19,
          18,    17,    16,    15,    14,    13,    12,    11,    10,
           9,     8,     7,     6,     5,     4, -1200,     2,     1,
           0])

In [30]:
#Location of (-1200)
idx = np.argwhere(A==-1200)[0][0]

In [31]:
idx

np.int64(3)

In [32]:
#change value 
A[idx] = 3

In [33]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
A = np.round(10*np.random.rand(5,4)) #  rows 5 and columns 4

In [35]:
A

array([[ 4.,  3.,  8.,  3.],
       [ 6.,  5.,  2.,  5.],
       [ 2.,  7.,  3.,  3.],
       [ 9., 10.,  7.,  4.],
       [ 0.,  4.,  1.,  0.]])

In [36]:
A[1,2] # rows 2 and column 3

np.float64(2.0)

In [37]:
A[1,:]

array([6., 5., 2., 5.])

In [38]:
A[1:3,2:4] #rows 2 -3 ambil column 3-4

array([[2., 5.],
       [3., 3.]])

In [39]:
#Linier algabra
import numpy.linalg as la

In [40]:
la.inv(np.random.rand(3,3))

array([[-0.44518502, -0.07061571,  1.3167901 ],
       [ 0.09473789,  1.10446966, -0.97230238],
       [ 1.17553882, -0.17290332, -0.38252877]])

In [41]:
A

array([[ 4.,  3.,  8.,  3.],
       [ 6.,  5.,  2.,  5.],
       [ 2.,  7.,  3.,  3.],
       [ 9., 10.,  7.,  4.],
       [ 0.,  4.,  1.,  0.]])

In [42]:
#sort
A.sort(axis=0) #sort atau mengurutkan secara rows

In [43]:
A

array([[ 0.,  3.,  1.,  0.],
       [ 2.,  4.,  2.,  3.],
       [ 4.,  5.,  3.,  3.],
       [ 6.,  7.,  7.,  4.],
       [ 9., 10.,  8.,  5.]])

In [44]:
A.sort(axis=1) #sort atau mengurutkan secara columns

In [45]:
A

array([[ 0.,  0.,  1.,  3.],
       [ 2.,  2.,  3.,  4.],
       [ 3.,  3.,  4.,  5.],
       [ 4.,  6.,  7.,  7.],
       [ 5.,  8.,  9., 10.]])

Numpy (More Indexing)

In [46]:
import numpy as np
A = np.arange(100)

In [47]:
B= A[[3,45,6]] #act as copy so if B change A doesnt change 

In [48]:
B

array([ 3, 45,  6])

In [49]:
B[0] = -4

In [50]:
B #Change

array([-4, 45,  6])

In [51]:
A # Doesnt Change

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
B=A[A<40]

In [53]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [54]:
B = A[(A<40) & (A > 30)]

In [55]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [56]:
# (&, |, ~) for array , (and, or, not) for single object

Numpy (Broadcasting)
#A + 5

Numpy (hstack, vstack,sort)

In [57]:
A = np.round(10*np.random.rand(2,3))

In [58]:
A

array([[5., 6., 0.],
       [6., 6., 8.]])

In [59]:
A + 3

array([[ 8.,  9.,  3.],
       [ 9.,  9., 11.]])

In [60]:
A + np.arange(2).reshape(2,1)

array([[5., 6., 0.],
       [7., 7., 9.]])

In [61]:
B = np.round(10*np.random.rand(2,2))

In [62]:
B

array([[5., 5.],
       [1., 4.]])

In [65]:
C = np.hstack ((A,B)) # menggabungkan secara horisontal

In [66]:
C

array([[5., 6., 0., 5., 5.],
       [6., 6., 8., 1., 4.]])

In [67]:
A = np.random.permutation(np.arange(10))

In [68]:
A

array([0, 2, 3, 4, 1, 8, 9, 5, 6, 7])

In [69]:
A.sort() #sort atau mengurutkan
#A = A[::-1] sort in descending
#A = A[::0] sort in ascending

In [70]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])